version: '3'

services:
  db:
    image: postgres
    container_name: feedget_postgres
    restart: always
    tty: true
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DATABASE: ${DATABASE_DATABASE}
